// 鉱物データ
const MINERALS_DATA = {
    minerals: [
        {
            id: 1,
            name_jp: "めのう",
            name_en: "AGATE",
            chemical_formula_html: "SiO<sub>2</sub>",
            origin: ["Brazil"],
            description: "硬度6.5～7 潜晶質縞状の珪酸で岩石の空隙に層状に沈殿したもの。容易に人工着色が行われる。",
            symmetry: "六方晶系",
            crystal_structure: "石英グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 2,
            name_jp: "鉄ばんざくろ石",
            name_en: "ALMANDINE",
            chemical_formula_html: "Fe<sub>3</sub>Al<sub>2</sub>(SiO<sub>4</sub>)<sub>3</sub>",
            origin: ["China"],
            description: "硬度7～7.5 鉄とアルミニウムを主成分とするガーネット。",
            symmetry: "等軸晶系",
            crystal_structure: "柘榴石グループ",
            habit: ["柱状"],
            occurrence: ["変成鉱物"],
            strunz_classification: "09.A門 ネソ珪酸塩鉱物"
        },
        {
            id: 3,
            name_jp: "アマゾナイト",
            name_en: "AMAZONITE",
            chemical_formula_html: "K(AlSi<sub>3</sub>O<sub>8</sub>)",
            origin: ["Russia"],
            description: "微量な鉛を含有するため青緑色を呈す。微斜長石に属す。",
            symmetry: "三斜晶系",
            crystal_structure: "長石グループ",
            habit: ["板状"],
            occurrence: ["造岩鉱物"],
            strunz_classification: "09.F門 テクト珪酸塩鉱物"
        },
        {
            id: 4,
            name_jp: "紫水晶",
            name_en: "AMETHYST",
            chemical_formula_html: "SiO<sub>2</sub>",
            origin: ["Brazil"],
            description: "有色の水晶。紫色は天然の放射能と微量の鉄イオンによる。",
            symmetry: "六方晶系",
            crystal_structure: "石英グループ",
            habit: ["柱状", "錐状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 5,
            name_jp: "燐灰石",
            name_en: "APATITE",
            chemical_formula_html: "Ca<sub>5</sub>(PO<sub>4</sub>)<sub>3</sub>F",
            origin: ["Mexico"],
            description: "硬度5 燐酸カルシウムに弗素が加わったもの。",
            symmetry: "六方晶系",
            crystal_structure: "燐灰石グループ",
            habit: ["柱状"],
            occurrence: ["造岩鉱物", "接触鉱物"],
            strunz_classification: "08族 燐酸塩鉱物"
        },
        {
            id: 6,
            name_jp: "魚眼石",
            name_en: "APOPHYLLITE",
            chemical_formula_html: "KCa<sub>4</sub>(Si<sub>4</sub>O<sub>10</sub>)<sub>2</sub>(F,OH)·8H<sub>2</sub>O",
            origin: ["India"],
            description: "正方錐形または柱状の結晶。一方向に完全な劈開(ヘキカイ)を持つ。",
            symmetry: "正方晶系",
            crystal_structure: "層状珪酸塩グループ",
            habit: ["柱状", "錐状"],
            occurrence: ["接触鉱物"],
            strunz_classification: "09.E門 フィロ珪酸塩鉱物"
        },
        {
            id: 7,
            name_jp: "アベンチュリン",
            name_en: "AVENTURINE",
            chemical_formula_html: "SiO<sub>2</sub>",
            origin: ["Brazil"],
            description: "緑色の雲母を含むため緑色となった石英。",
            symmetry: "六方晶系",
            crystal_structure: "石英グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 8,
            name_jp: "藍銅鉱",
            name_en: "AZURITE",
            chemical_formula_html: "Cu<sub>3</sub>(OH)<sub>2</sub>(CO<sub>3</sub>)<sub>2</sub>",
            origin: ["Morocco"],
            description: "硬度3.5～4 銅鉱床酸化帯に孔雀石や褐鉄鉱に伴って産出する。",
            symmetry: "単斜晶系",
            crystal_structure: "炭酸塩グループ",
            habit: ["板状", "柱状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "05族 炭酸塩鉱物"
        },
        {
            id: 9,
            name_jp: "縞状鉄鉱",
            name_en: "BANDED IRON",
            chemical_formula_html: "FeCO<sub>3</sub>/HFeO<sub>2</sub>/Fe<sub>2</sub>O<sub>3</sub>/Fe<sub>3</sub>O<sub>4</sub>",
            origin: ["Australia"],
            description: "先カンブリア時代(約25億年前)、海水中の鉄分とシアノバクテリア(ラン藻類)が作り出した酸素が結びついて形成された鉄鉱石。",
            symmetry: "非晶質",
            crystal_structure: "酸化鉱物グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "04族 酸化鉱物"
        },
        {
            id: 10,
            name_jp: "黒雲母",
            name_en: "BIOTITE",
            chemical_formula_html: "K(Fe,Mg)<sub>3</sub>(AlSi<sub>3</sub>O<sub>10</sub>)(OH,F)<sub>2</sub>",
            origin: ["Canada"],
            description: "硬度2～3 オブラートのように薄く劈開(ヘキカイ)し10ミクロまで剥がせる。",
            symmetry: "単斜晶系",
            crystal_structure: "雲母グループ",
            habit: ["板状"],
            occurrence: ["造岩鉱物"],
            strunz_classification: "09.E門 フィロ珪酸塩鉱物"
        },
        {
            id: 11,
            name_jp: "斑銅鉱",
            name_en: "BORNITE",
            chemical_formula_html: "Cu<sub>5</sub>FeS<sub>4</sub>",
            origin: ["Mexico"],
            description: "高品位の銅鉱で銅、鉄、硫黄からなる鉱物。",
            symmetry: "等軸晶系",
            crystal_structure: "硫化鉱物グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "02族 硫化鉱物"
        },
        {
            id: 12,
            name_jp: "方解石",
            name_en: "CALCITE(Iceland Spar)",
            chemical_formula_html: "CaCO<sub>3</sub>",
            origin: ["Mexico"],
            description: "硬度3 炭酸カルシウムの鉱物で最もポピュラーな脈石鉱物。複屈折によって石を透して物を見ると二重に見える。極めて完全な劈開(ヘキカイ)によりマッチ箱をつぶしたような形に割れる。",
            symmetry: "六方晶系",
            crystal_structure: "炭酸塩グループ",
            habit: ["柱状", "板状"],
            occurrence: ["造岩鉱物", "鉱石鉱物"],
            strunz_classification: "05族 炭酸塩鉱物"
        },
        {
            id: 17,
            name_jp: "黄銅鉱",
            name_en: "CHALCOPYRITE",
            chemical_formula_html: "CuFeS<sub>2</sub>",
            origin: ["Mexico"],
            description: "代表的な銅鉱石。黄鉄鉱についでポピュラーな硫化鉱物。",
            symmetry: "正方晶系",
            crystal_structure: "硫化鉱物グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "02族 硫化鉱物"
        },
        {
            id: 18,
            name_jp: "珪孔雀石",
            name_en: "CHRYSOCOLLA",
            chemical_formula_html: "(Cu,Al)<sub>2</sub>H<sub>2</sub>Si<sub>2</sub>O<sub>5</sub>(OH)<sub>4</sub>·nH<sub>2</sub>O",
            origin: ["Arizona, U.S.A."],
            description: "硬度2.5 銅鉱床に産出。皮殻状、葡萄状をなす。",
            symmetry: "非晶質",
            crystal_structure: "珪酸塩グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 19,
            name_jp: "自然銅",
            name_en: "COPPER",
            chemical_formula_html: "Cu",
            origin: ["Michigan, U.S.A."],
            description: "硬度2.5～3 熱及び電気の良導体で展性、延性に富む。",
            symmetry: "等軸晶系",
            crystal_structure: "元素鉱物グループ",
            habit: ["塊状", "樹枝状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "01族 元素鉱物"
        },
        {
            id: 20,
            name_jp: "鋼玉(コランダム)",
            name_en: "CORUNDUM",
            chemical_formula_html: "Al<sub>2</sub>O<sub>3</sub>",
            origin: ["South Africa"],
            description: "硬度9 酸化アルミニウムの鉱物。",
            symmetry: "六方晶系",
            crystal_structure: "酸化鉱物グループ",
            habit: ["柱状", "錐状"],
            occurrence: ["変成鉱物", "鉱石鉱物"],
            strunz_classification: "04族 酸化鉱物"
        },
        {
            id: 21,
            name_jp: "氷晶石",
            name_en: "CRYOLITE",
            chemical_formula_html: "Na<sub>3</sub>AlF<sub>6</sub>",
            origin: ["Greenland"],
            description: "「融けない氷」といわれ、白色塊状でグリーンランドに産する。",
            symmetry: "単斜晶系",
            crystal_structure: "ハロゲン化鉱物グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "03族 ハロゲン化鉱物"
        },
        {
            id: 22,
            name_jp: "苦灰石",
            name_en: "DOLOMITE",
            chemical_formula_html: "CaMg(CO<sub>3</sub>)<sub>2</sub>",
            origin: ["Morocco"],
            description: "和名は苦しそうな名前であるが苦はマグネシウム、灰は石灰を意味する。",
            symmetry: "六方晶系",
            crystal_structure: "炭酸塩グループ",
            habit: ["板状", "柱状"],
            occurrence: ["造岩鉱物"],
            strunz_classification: "05族 炭酸塩鉱物"
        },
        {
            id: 23,
            name_jp: "長石",
            name_en: "FELDSPAR",
            chemical_formula_html: "K(AlSi<sub>3</sub>O<sub>8</sub>)",
            origin: ["India"],
            description: "長石グループは地殻の重量の50％を占める鉱物。",
            symmetry: "三斜晶系",
            crystal_structure: "長石グループ",
            habit: ["板状", "柱状"],
            occurrence: ["造岩鉱物"],
            strunz_classification: "09.F門 テクト珪酸塩鉱物"
        },
        {
            id: 24,
            name_jp: "蛍石",
            name_en: "FLUORITE",
            chemical_formula_html: "CaF<sub>2</sub>",
            origin: ["Mexico", "China"],
            description: "熱すると蛍光を放つ。又、紫外線で蛍光を発するものもある。結晶は6面体、8面体、斜方12面体。",
            symmetry: "等軸晶系",
            crystal_structure: "ハロゲン化鉱物グループ",
            habit: ["立方体", "八面体"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "03族 ハロゲン化鉱物"
        },
        {
            id: 26,
            name_jp: "クロム白雲母",
            name_en: "FUCHSITE",
            chemical_formula_html: "KAl<sub>2</sub>(AlSi<sub>3</sub>O<sub>10</sub>)(OH,F)<sub>2</sub>",
            origin: ["Brazil"],
            description: "硬度2.5～3 クロムの酸化物の混入で緑色になった白雲母。",
            symmetry: "単斜晶系",
            crystal_structure: "雲母グループ",
            habit: ["板状"],
            occurrence: ["変成鉱物"],
            strunz_classification: "09.E門 フィロ珪酸塩鉱物"
        },
        {
            id: 27,
            name_jp: "方鉛鉱",
            name_en: "GALENA",
            chemical_formula_html: "PbS",
            origin: ["Missouri, U.S.A."],
            description: "硬度2.5～3 鉛の鉱石。",
            symmetry: "等軸晶系",
            crystal_structure: "硫化鉱物グループ",
            habit: ["立方体"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "02族 硫化鉱物"
        },
        {
            id: 28,
            name_jp: "石墨",
            name_en: "GRAPHITE",
            chemical_formula_html: "C",
            origin: ["China"],
            description: "硬度1 電導性にすぐれ電極や鉛筆の芯などに利用される。",
            symmetry: "六方晶系",
            crystal_structure: "元素鉱物グループ",
            habit: ["板状"],
            occurrence: ["変成鉱物"],
            strunz_classification: "01族 元素鉱物"
        },
        {
            id: 29,
            name_jp: "灰ばん柘榴石",
            name_en: "GROSSULAR",
            chemical_formula_html: "Ca<sub>3</sub>Al<sub>2</sub>(SiO<sub>4</sub>)<sub>3</sub>",
            origin: ["Mexico"],
            description: "アルミニウムを含む淡緑色のざくろ石。",
            symmetry: "等軸晶系",
            crystal_structure: "柘榴石グループ",
            habit: ["柱状"],
            occurrence: ["変成鉱物"],
            strunz_classification: "09.A門 ネソ珪酸塩鉱物"
        },
        {
            id: 30,
            name_jp: "迪石膏(ジプサム)",
            name_en: "GYPSUM",
            chemical_formula_html: "CaSO<sub>4</sub>·2H<sub>2</sub>O",
            origin: ["Utah, U.S.A."],
            description: "硬度2 最も普通に産出する硫酸塩鉱物。石膏のうち透明度の高い柱状の結晶を成すものを迪石膏という。",
            symmetry: "単斜晶系",
            crystal_structure: "硫酸塩グループ",
            habit: ["柱状", "板状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "07族 硫酸塩鉱物"
        },
        {
            id: 31,
            name_jp: "ハックマン石",
            name_en: "HACKMANITE",
            chemical_formula_html: "Na<sub>8</sub>Al<sub>6</sub>Si<sub>6</sub>O<sub>24</sub>(Cl,S)<sub>2</sub>",
            origin: ["Canada"],
            description: "方ソーダ石に不純物として硫黄を含む鉱物。紫外線により蛍光を発する。",
            symmetry: "等軸晶系",
            crystal_structure: "長石グループ",
            habit: ["塊状"],
            occurrence: ["接触鉱物"],
            strunz_classification: "09.F門 テクト珪酸塩鉱物"
        },
        {
            id: 32,
            name_jp: "碧玉(へきぎょく)",
            name_en: "JASPER",
            chemical_formula_html: "SiO<sub>2</sub>",
            origin: ["South Africa"],
            description: "不純な玉髄質の塊状石英で酸化鉄により赤褐色を呈する。",
            symmetry: "非晶質",
            crystal_structure: "石英グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 33,
            name_jp: "藍晶石",
            name_en: "KYANITE",
            chemical_formula_html: "Al<sub>2</sub>SiO<sub>5</sub>",
            origin: ["Brazil"],
            description: "硬度4.5～7と方向によって硬度が異なる。",
            symmetry: "三斜晶系",
            crystal_structure: "珪酸塩グループ",
            habit: ["板状", "柱状"],
            occurrence: ["変成鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 34,
            name_jp: "青金石",
            name_en: "LAPIS-LAZULI",
            chemical_formula_html: "(Na,Ca)<sub>7～8</sub>(Al,Si)<sub>12</sub>(O,S)<sub>24</sub>[(SO<sub>4</sub>),Cl<sub>2</sub>,(OH)<sub>2</sub>]",
            origin: ["Afganistan"],
            description: "硬度5～5.5 群青色の顔料にもなる珪酸塩鉱物。",
            symmetry: "等軸晶系",
            crystal_structure: "長石グループ",
            habit: ["塊状"],
            occurrence: ["変成鉱物"],
            strunz_classification: "09.F門 テクト珪酸塩鉱物"
        },
        {
            id: 35,
            name_jp: "リチア雲母",
            name_en: "LEPIDOLITE",
            chemical_formula_html: "K(Li,Al)<sub>3</sub>(AlSi<sub>3</sub>O<sub>10</sub>)(OH,F)<sub>2</sub>",
            origin: ["Brazil"],
            description: "硬度2.5～4 リチウムの原料。",
            symmetry: "単斜晶系",
            crystal_structure: "雲母グループ",
            habit: ["板状"],
            occurrence: ["造岩鉱物"],
            strunz_classification: "09.E門 フィロ珪酸塩鉱物"
        },
        {
            id: 36,
            name_jp: "磁鉄鉱",
            name_en: "LODESTONE",
            chemical_formula_html: "FeFe<sub>2</sub>O<sub>4</sub>",
            origin: ["Utah, U.S.A."],
            description: "硬度5.5～6.5 強い磁性があり鉄を引きつける天然磁石。",
            symmetry: "等軸晶系",
            crystal_structure: "スピネルグループ",
            habit: ["塊状", "八面体"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "04族 酸化鉱物"
        },
        {
            id: 37,
            name_jp: "孔雀石",
            name_en: "MALACHITE",
            chemical_formula_html: "Cu<sub>2</sub>(CO<sub>3</sub>)(OH)<sub>2</sub>",
            origin: ["D.R Congo"],
            description: "硬度3.5～4 銅の鉱床にできる鉱物。",
            symmetry: "単斜晶系",
            crystal_structure: "炭酸塩グループ",
            habit: ["針状", "塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "05族 炭酸塩鉱物"
        },
        {
            id: 38,
            name_jp: "白雲母",
            name_en: "MUSCOVITE",
            chemical_formula_html: "KAl<sub>2</sub>(AlSi<sub>3</sub>O<sub>10</sub>)(OH,F)<sub>2</sub>",
            origin: ["Brazil"],
            description: "硬度2.5～3 薄くはがれ、すぐれた絶縁性があり熱も伝えない。",
            symmetry: "単斜晶系",
            crystal_structure: "雲母グループ",
            habit: ["板状"],
            occurrence: ["造岩鉱物"],
            strunz_classification: "09.E門 フィロ珪酸塩鉱物"
        },
        {
            id: 39,
            name_jp: "黒曜石",
            name_en: "OBSIDIAN",
            chemical_formula_html: "SiO<sub>2</sub>",
            origin: ["Hokkaido,Japan", "Arizona, U.S.A."],
            description: "貝殻状断口が特徴。珪酸質マグマが急冷してできたガラス質の結晶。",
            symmetry: "非晶質",
            crystal_structure: "珪酸塩グループ",
            habit: ["塊状"],
            occurrence: ["火成岩"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 41,
            name_jp: "かんらん石",
            name_en: "OLIVINE",
            chemical_formula_html: "(Mg,Fe)<sub>2</sub>SiO<sub>4</sub>",
            origin: ["Arizona, U.S.A."],
            description: "主成分は珪酸マグネシウム。高温の火山岩中に誕生する。",
            symmetry: "斜方晶系",
            crystal_structure: "珪酸塩グループ",
            habit: ["粒状"],
            occurrence: ["造岩鉱物"],
            strunz_classification: "09.A門 ネソ珪酸塩鉱物"
        },
        {
            id: 42,
            name_jp: "蛋白石",
            name_en: "OPAL",
            chemical_formula_html: "SiO<sub>2</sub>・nH<sub>2</sub>O",
            origin: ["Oregon, U.S.A.", "Mexico"],
            description: "硬度5～6.5 珪酸鉱物、非晶質でSiO2(二酸化珪素)に水が加わった鉱物。美しい遊色を示すものがあり宝石として珍重される。",
            symmetry: "非晶質",
            crystal_structure: "珪酸塩グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 44,
            name_jp: "砂金",
            name_en: "PLACER-GOLD",
            chemical_formula_html: "Au",
            origin: ["Australia"],
            description: "硬度2.5～3 金の鉱床が風化し川へと流れ、砂と一緒に堆積した自然金。",
            symmetry: "等軸晶系",
            crystal_structure: "元素鉱物グループ",
            habit: ["粒状", "塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "01族 元素鉱物"
        },




        {
            id: 45,
            name_jp: "黄鉄鉱",
            name_en: "PYRITE",
            chemical_formula_html: "FeS<sub>2</sub>",
            origin: ["Peru"],
            description: "硬度6～6.5 最も普通に産出する硫化鉱物。",
            symmetry: "等軸晶系",
            crystal_structure: "硫化鉱物グループ",
            habit: ["立方体", "八面体"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "02族 硫化鉱物"
        },
        {
            id: 46,
            name_jp: "水晶",
            name_en: "QUARTZ-CRYSTAL",
            chemical_formula_html: "SiO<sub>2</sub>",
            origin: ["Arkansas, U.S.A."],
            description: "一般的な六角柱状の石英の結晶。柱面は常に60度で交わる。",
            symmetry: "六方晶系",
            crystal_structure: "石英グループ",
            habit: ["柱状", "錐状"],
            occurrence: ["造岩鉱物", "鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 47,
            name_jp: "石英",
            name_en: "QUARTZ",
            chemical_formula_html: "SiO<sub>2</sub>",
            origin: ["Brazil"],
            description: "最もポピュラーな鉱物でガラスの原料ともなる。",
            symmetry: "六方晶系",
            crystal_structure: "石英グループ",
            habit: ["柱状", "塊状"],
            occurrence: ["造岩鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 48,
            name_jp: "紅石英",
            name_en: "ROSE-QUARTZ",
            chemical_formula_html: "SiO<sub>2</sub>",
            origin: ["Brazil"],
            description: "ローズクォーツの名で親しまれるピンク色の石英。",
            symmetry: "六方晶系",
            crystal_structure: "石英グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 49,
            name_jp: "迪石膏(砂漠のバラ)",
            name_en: "SELENITE-ROSE",
            chemical_formula_html: "CaSO<sub>4</sub>·2H<sub>2</sub>O",
            origin: ["Mexico"],
            description: "硬度2 最も普通に産出する硫酸塩鉱物。石膏のうち透明度の高い柱状の結晶を成すものを迪石膏という。",
            symmetry: "単斜晶系",
            crystal_structure: "硫酸塩グループ",
            habit: ["板状", "花弁状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "07族 硫酸塩鉱物"
        },
        {
            id: 50,
            name_jp: "方ソーダ石",
            name_en: "SODALITE",
            chemical_formula_html: "Na<sub>4</sub>(SiAl<sub>3</sub>)O<sub>12</sub>Cl",
            origin: ["Namibia"],
            description: "硬度5.5～6 青金石(ラピスラズリ)を構成する鉱物のひとつ。",
            symmetry: "等軸晶系",
            crystal_structure: "長石グループ",
            habit: ["塊状"],
            occurrence: ["造岩鉱物"],
            strunz_classification: "09.F門 テクト珪酸塩鉱物"
        },
        {
            id: 51,
            name_jp: "輝安鉱",
            name_en: "STIBNITE",
            chemical_formula_html: "Sb<sub>2</sub>S<sub>3</sub>",
            origin: ["China"],
            description: "重要なアンチモニー鉱石。硬度2とやわらかい。",
            symmetry: "斜方晶系",
            crystal_structure: "硫化鉱物グループ",
            habit: ["針状", "柱状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "02族 硫化鉱物"
        },
        {
            id: 52,
            name_jp: "硫黄",
            name_en: "SULFUR",
            chemical_formula_html: "S",
            origin: ["Indonesia"],
            description: "硬度1.5～2.5 斜方結晶の集合体で燃やすと硫化水素を出す。",
            symmetry: "斜方晶系",
            crystal_structure: "元素鉱物グループ",
            habit: ["塊状", "粒状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "01族 元素鉱物"
        },
        {
            id: 53,
            name_jp: "滑石",
            name_en: "TALC",
            chemical_formula_html: "Mg<sub>3</sub>(SiO<sub>10</sub>)(OH)<sub>2</sub>",
            origin: ["Australia"],
            description: "モース硬度1 印材、薬品、製紙などで幅広く利用されている。",
            symmetry: "単斜晶系",
            crystal_structure: "層状珪酸塩グループ",
            habit: ["板状", "塊状"],
            occurrence: ["変成鉱物", "粘土鉱物"],
            strunz_classification: "09.E門 フィロ珪酸塩鉱物"
        },
        {
            id: 54,
            name_jp: "虎目石",
            name_en: "TIGER-EYE",
            chemical_formula_html: "SiO<sub>2</sub>",
            origin: ["South Africa"],
            description: "石綿と石英から成る。石に含まれる鉄分によって縞模様がつくられる。",
            symmetry: "非晶質",
            crystal_structure: "石英グループ",
            habit: ["繊維状", "塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 55,
            name_jp: "黄玉",
            name_en: "TOPAZ",
            chemical_formula_html: "Al<sub>2</sub>SiO<sub>4</sub>(F,OH)<sub>2</sub>",
            origin: ["Utah, U.S.A."],
            description: "硬度8 日本でも産出する宝石鉱物。",
            symmetry: "斜方晶系",
            crystal_structure: "珪酸塩グループ",
            habit: ["柱状", "錐状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09族 珪酸塩鉱物"
        },
        {
            id: 56,
            name_jp: "電気石",
            name_en: "TOURMALINE",
            chemical_formula_html: "NaFe<sub>3</sub>Al<sub>6</sub>(BO<sub>3</sub>)Si<sub>6</sub>O<sub>18</sub>(OH)<sub>4</sub>",
            origin: ["Brazil"],
            description: "硬度7～7.5 火成岩、変成岩中に産出する。",
            symmetry: "六方晶系",
            crystal_structure: "環状珪酸塩グループ",
            habit: ["柱状", "錐状"],
            occurrence: ["造岩鉱物", "接触鉱物"],
            strunz_classification: "09.C門 シクロ珪酸塩鉱物"
        },
        {
            id: 57,
            name_jp: "トルコ石",
            name_en: "TURQUOISE",
            chemical_formula_html: "CuAl<sub>6</sub>(PO<sub>4</sub>)<sub>4</sub>(OH)<sub>8</sub>·4H<sub>2</sub>O",
            origin: ["Nevada, U.S.A."],
            description: "硬度5～6 結晶することはまれで塊状ないし皮膜上に産出する。",
            symmetry: "三斜晶系",
            crystal_structure: "燐酸塩グループ",
            habit: ["塊状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "08族 燐酸塩鉱物"
        },
        {
            id: 58,
            name_jp: "曹灰硼石(テレビ石)",
            name_en: "ULEXITE",
            chemical_formula_html: "NaCaB<sub>5</sub>O<sub>9</sub>·8H<sub>2</sub>O",
            origin: ["California, U.S.A."],
            description: "硬度2.5 純白で絹糸光沢、繊維状結晶の集合体。グラスファイバーと同じ効果で下のものが浮き上がって見える。",
            symmetry: "三斜晶系",
            crystal_structure: "硼酸塩鉱物グループ",
            habit: ["繊維状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "06族 硼酸塩鉱物"
        },
        {
            id: 59,
            name_jp: "バナジン鉛鉱",
            name_en: "VANADINITE",
            chemical_formula_html: "Pb<sub>5</sub>(VO<sub>4</sub>)<sub>3</sub>Cl",
            origin: ["Morocco"],
            description: "元素バナジウムを主成分とする鉱物。6角柱状に結晶する。",
            symmetry: "六方晶系",
            crystal_structure: "燐灰石グループ",
            habit: ["柱状", "錐状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "08族 バナジン酸塩鉱物"
        },
        {
            id: 60,
            name_jp: "珪酸亜鉛鉱",
            name_en: "WILLEMITE",
            chemical_formula_html: "Zn<sub>2</sub>SiO<sub>4</sub>",
            origin: ["New Jersey, U.S.A."],
            description: "紫外線により鮮やかな輝緑色の蛍光を発する。",
            symmetry: "六方晶系",
            crystal_structure: "珪酸塩グループ",
            habit: ["柱状", "粒状"],
            occurrence: ["鉱石鉱物"],
            strunz_classification: "09.A門 ネソ珪酸塩鉱物"
        }
    ]
};

// アルファベット索引を生成
const generateAlphabetIndex = () => {
    const minerals = MINERALS_DATA.minerals;
    const letters = new Set(minerals.map(m => m.name_en.charAt(0)));
    return Array.from(letters).sort();
};

// 特定のアルファベットで始まる鉱物を取得
const getMineralsByLetter = (letter) => {
    return MINERALS_DATA.minerals.filter(m => m.name_en.startsWith(letter));
};

// IDで鉱物を取得
const getMineralById = (id) => {
    return MINERALS_DATA.minerals.find(m => m.id === id);
};

// 鉱物データをソート
MINERALS_DATA.minerals.sort((a, b) => a.name_en.localeCompare(b.name_en));
